#!/bin/sh
# workspace claude-hook — Claude Code session hooks for linked Git worktrees.
#
# Claude Code has no native setup or cleanup script, so `workspace init` wires
# these into .claude/settings.json. Measured desktop app behavior they rely on:
#
#   - Hooks run from the original checkout; the session's worktree is only
#     available as "cwd" in the JSON on stdin.
#   - A new session fires SessionStart "startup"; unarchiving fires "resume".
#   - Archiving fires SessionEnd "other" after releasing the worktree's branch
#     (detached HEAD). The worktree directory is never deleted.
#
# session-start bootstraps the worktree once and records whether the session
# started on a branch. session-end archives only when a session that started
# on its branch ends detached, which is what archive does. A session that
# starts or resumes detached (Codex worktrees, or an unarchive that could not
# reattach its branch) is never archived automatically: when quit and archive
# look identical, leaving databases behind is safer than dropping them. Run
# `bin/workspace archive` by hand in that case.
#
# State lives in the worktree's private Git directory:
#   workspace-claude-branch         branch the current session started on
#   workspace-claude-bootstrapping  PID of a bootstrap still setting up
#   workspace-claude-archiving      PID of a background archive still running
#   workspace-claude-archived       teardown ran; next start must fully bootstrap
#   workspace-claude.log            background archive output

set -e

WORKSPACE_LIB="$(cd "$(dirname "$0")" && pwd)"
. "$WORKSPACE_LIB/common.sh"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ] || [ -z "${1:-}" ]; then
  cat <<'EOF'
Usage: workspace claude-hook <session-start|session-end>

Reads Claude Code hook JSON on stdin. Generated by workspace init in
.claude/settings.json; not normally run by hand.

  session-start  Bootstrap the session's linked Git worktree once
  session-end    Archive the worktree in the background after Claude Code
                 archives the session (its branch was released)
EOF
  [ -n "${1:-}" ] && exit 0
  exit 1
fi

_claude_event="$1"
_claude_input=$(cat)

# Paths with JSON escapes are not supported; fail closed rather than guess.
_claude_cwd=$(printf '%s' "$_claude_input" | tr -d '\n' \
  | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"\\]*\)".*/\1/p')
[ -n "$_claude_cwd" ] && [ -d "$_claude_cwd" ] || exit 0
cd "$_claude_cwd"

# The session may have moved into a subdirectory; lifecycle commands run from
# the worktree root.
_claude_paths=$(git rev-parse --show-toplevel --absolute-git-dir 2>/dev/null) || exit 0
{ read -r _claude_top; read -r _claude_git_dir; } <<EOF
$_claude_paths
EOF
cd "$_claude_top"

# Only unmanaged linked Git worktrees of projects set up with workspace init.
# The original checkout keeps its own lifecycle, and Conductor-family managers
# run their own setup and archive.
resolve_workspace
[ "$WORKSPACE_PROVIDER" = "git" ] || exit 0
[ -x bin/workspace ] || exit 0

_claude_branch_marker="$_claude_git_dir/workspace-claude-branch"
_claude_bootstrapping_marker="$_claude_git_dir/workspace-claude-bootstrapping"
_claude_archiving_marker="$_claude_git_dir/workspace-claude-archiving"
_claude_archived_marker="$_claude_git_dir/workspace-claude-archived"
_claude_log="$_claude_git_dir/workspace-claude.log"

# Publish a PID marker by rename, so readers never see a partial file.
_claude_write_pid() {
  printf '%s\n' "$2" > "$1.$$" && mv -f "$1.$$" "$1" || { rm -f "$1.$$"; return 1; }
}

# The background archive runs as `sh -c ... workspace-claude-archive`. A PID
# left by a killed archive (reboot, force quit) is trusted only while it still
# belongs to an archive job, not a reused process ID; otherwise the stale
# marker is removed. The job's own wait loop below follows the same rule.
_claude_archive_running() {
  [ -f "$_claude_archiving_marker" ] || return 1
  _claude_archive_pid=$(cat "$_claude_archiving_marker" 2>/dev/null || true)
  case "$(ps -ww -p "${_claude_archive_pid:-0}" -o command= 2>/dev/null || true)" in
    *workspace-claude-archive*) return 0 ;;
  esac
  rm -f "$_claude_archiving_marker"
  return 1
}

case "$_claude_event" in
  session-start)
    # Unarchiving can race a background archive from the previous session.
    # Let it finish so it cannot drop databases after setup recreates them,
    # or forget the branch recorded below once it completes. There is no
    # separate limit: if the hook's own timeout stops this wait, nothing has
    # been recorded yet and the next session start tries again.
    while _claude_archive_running; do
      sleep 0.2
    done

    # Only a session that starts on a branch can later be recognized as
    # archived, even if an earlier session owned one.
    if _claude_branch=$(git symbolic-ref -q --short HEAD); then
      printf '%s\n' "$_claude_branch" > "$_claude_branch_marker"
    else
      rm -f "$_claude_branch_marker"
    fi

    # An unarchived worktree may still look set up to --once, so after a hook
    # archive run a full bootstrap. The archived marker stays until it succeeds.
    _claude_once=--once
    [ ! -f "$_claude_archived_marker" ] || _claude_once=

    # Archiving during setup waits for the bootstrapping marker, so it cannot
    # drop databases that setup is still creating. The marker is claimed with
    # this hook's PID before setup starts, then handed to the bootstrap process
    # itself, so if Claude Code stops this hook mid-setup the archive still
    # waits for the setup that keeps running. It is removed only while it still
    # names this hook or its finished bootstrap, so an overlapping session
    # start keeps its own marker.
    _claude_bootstrap=""
    _claude_release_bootstrap() {
      if [ -n "$_claude_bootstrap" ] && kill -0 "$_claude_bootstrap" 2>/dev/null; then
        return 0
      fi
      case "$(cat "$_claude_bootstrapping_marker" 2>/dev/null || true)" in
        "$$"|"${_claude_bootstrap:-$$}") rm -f "$_claude_bootstrapping_marker" ;;
      esac
    }
    trap '_claude_release_bootstrap' EXIT
    _claude_write_pid "$_claude_bootstrapping_marker" "$$"
    # Bootstrap output goes to stderr so it stays out of Claude's context.
    sh "$WORKSPACE_LIB/bootstrap.sh" $_claude_once >&2 &
    _claude_bootstrap=$!
    _claude_write_pid "$_claude_bootstrapping_marker" "$_claude_bootstrap"

    wait "$_claude_bootstrap" || exit 1
    # An archive that started while setup ran owns the teardown record now.
    if [ -z "$_claude_once" ] && ! _claude_archive_running; then
      rm -f "$_claude_archived_marker"
    fi
    exit 0
    ;;
  session-end)
    [ -f "$_claude_branch_marker" ] || exit 0
    git symbolic-ref -q HEAD >/dev/null && exit 0
    # A rebase or bisect detaches HEAD on purpose; that is not an archive.
    for _claude_in_progress in rebase-merge rebase-apply BISECT_LOG; do
      [ ! -e "$_claude_git_dir/$_claude_in_progress" ] || exit 0
    done
    ! _claude_archive_running || exit 0

    # SessionEnd hooks get at most 60 seconds; archive may need longer. The
    # job runs in its own session so it survives Claude Code stopping the
    # hook's process group (macOS has no setsid command, but ships Perl), and
    # publishes its own PID before working.
    #
    # The job first waits for a bootstrap still setting up, or a session start
    # about to launch one; they are matched by expanded paths, which never
    # appear in the job's own command line. It then marks the worktree for a
    # full bootstrap, since teardown may stop partway. The session branch is
    # forgotten only after a complete archive, so a failed one is attempted
    # again on the next archive.
    if command -v setsid >/dev/null 2>&1; then
      set -- setsid
    elif command -v perl >/dev/null 2>&1; then
      set -- perl -MPOSIX=setsid -e 'setsid(); exec @ARGV or die "exec: $!"'
    else
      set --
    fi
    "$@" nohup sh -c '
      printf "%s\n" "$$" > "$4.$$" && mv -f "$4.$$" "$4"
      while [ -f "$5" ]; do
        _pid=$(cat "$5" 2>/dev/null || true)
        case "$(ps -ww -p "${_pid:-0}" -o command= 2>/dev/null || true)" in
          *"$1/bootstrap.sh"*|*"$1/claude_hook.sh session-start"*) sleep 0.2 ;;
          *) [ "$(cat "$5" 2>/dev/null || true)" != "$_pid" ] || rm -f "$5" ;;
        esac
      done
      printf "=== archive %s\n" "$(date)"
      : > "$3"
      if sh "$1/archive.sh"; then
        rm -f "$2"
      else
        echo "Archive failed; it will be retried the next time this session is archived."
      fi
      rm -f "$4"
    ' workspace-claude-archive "$WORKSPACE_LIB" "$_claude_branch_marker" \
      "$_claude_archived_marker" "$_claude_archiving_marker" \
      "$_claude_bootstrapping_marker" >> "$_claude_log" 2>&1 &
    _claude_job=$!
    # Return only once the job is visible to a session start that follows.
    while [ ! -s "$_claude_archiving_marker" ] && kill -0 "$_claude_job" 2>/dev/null; do
      sleep 0.1
    done
    exit 0
    ;;
  *)
    echo "workspace claude-hook: unknown event '$_claude_event'" >&2
    exit 1
    ;;
esac
