#!/bin/sh
# workspace claude-hook — Claude Code session hooks for linked Git worktrees.
#
# Claude Code has no native setup or cleanup script, so `workspace init` wires
# these into .claude/settings.json. Measured desktop app behavior they rely on:
#
#   - Hooks run from the original checkout; the session's worktree is only
#     available as "cwd" in the JSON on stdin.
#   - A new session fires SessionStart "startup"; unarchiving fires "resume".
#   - Archiving fires SessionEnd "other" after releasing the worktree's branch
#     (detached HEAD). The worktree directory is never deleted.
#
# session-start bootstraps the worktree once and remembers which branch the
# session owns. session-end archives only when that remembered branch has been
# released, which separates archive from quitting the app or a stopped
# process, and never touches worktrees that started detached (Codex).
#
# State lives in the worktree's private Git directory:
#   workspace-claude-branch     branch the worktree's session owns; kept across
#                               archive so an unarchive that cannot reattach
#                               the branch still owns, and later archives, it
#   workspace-claude-archiving  PID of a background archive still running
#   workspace-claude-archived   teardown state: started, failed, or complete.
#                               Present means the next start must fully
#                               bootstrap; "complete" means do not archive again
#   workspace-claude.log        background archive output

set -e

WORKSPACE_LIB="$(cd "$(dirname "$0")" && pwd)"
. "$WORKSPACE_LIB/common.sh"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ] || [ -z "${1:-}" ]; then
  cat <<'EOF'
Usage: workspace claude-hook <session-start|session-end>

Reads Claude Code hook JSON on stdin. Generated by workspace init in
.claude/settings.json; not normally run by hand.

  session-start  Bootstrap the session's linked Git worktree once
  session-end    Archive the worktree in the background after Claude Code
                 archives the session (its branch was released)
EOF
  [ -n "${1:-}" ] && exit 0
  exit 1
fi

_claude_event="$1"
_claude_input=$(cat)

# Paths with JSON escapes are not supported; fail closed rather than guess.
_claude_cwd=$(printf '%s' "$_claude_input" | tr -d '\n' \
  | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"\\]*\)".*/\1/p')
[ -n "$_claude_cwd" ] && [ -d "$_claude_cwd" ] || exit 0
_claude_source=$(printf '%s' "$_claude_input" | tr -d '\n' \
  | sed -n 's/.*"source"[[:space:]]*:[[:space:]]*"\([a-z_]*\)".*/\1/p')
cd "$_claude_cwd"

# The session may have moved into a subdirectory; lifecycle commands run from
# the worktree root.
_claude_top=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$_claude_top"

# Only unmanaged linked Git worktrees. The original checkout keeps its own
# lifecycle, and Conductor-family managers run their own setup and archive.
resolve_workspace
[ "$WORKSPACE_PROVIDER" = "git" ] || exit 0
[ -x bin/workspace ] || exit 0

_claude_git_dir=$(git rev-parse --absolute-git-dir)
_claude_branch_marker="$_claude_git_dir/workspace-claude-branch"
_claude_archiving_marker="$_claude_git_dir/workspace-claude-archiving"
_claude_archived_marker="$_claude_git_dir/workspace-claude-archived"
_claude_log="$_claude_git_dir/workspace-claude.log"

# The background archive runs as `sh -c ... workspace-claude-archive`, so a
# PID left behind by a killed archive (reboot, force quit) is only trusted
# while it still belongs to an archive job and not a reused process ID.
_claude_archive_running() {
  [ -f "$_claude_archiving_marker" ] || return 1
  _claude_archive_pid=$(cat "$_claude_archiving_marker" 2>/dev/null || true)
  if [ -n "$_claude_archive_pid" ]; then
    case "$(ps -p "$_claude_archive_pid" -o command= 2>/dev/null || true)" in
      *workspace-claude-archive*) return 0 ;;
    esac
  fi
  # The archive died without cleaning up; its archived marker already forces
  # a full bootstrap.
  rm -f "$_claude_archiving_marker"
  return 1
}

case "$_claude_event" in
  session-start)
    # Unarchiving can race a background archive from the previous session.
    # Let it finish so it cannot drop databases after setup recreates them,
    # or forget the branch recorded below once it completes. There is no
    # separate limit: if the hook's own timeout stops this wait, nothing has
    # been recorded yet and the next session start tries again.
    while _claude_archive_running; do
      sleep 1
    done

    if _claude_branch=$(git symbolic-ref -q --short HEAD); then
      printf '%s\n' "$_claude_branch" > "$_claude_branch_marker"
    elif [ "$_claude_source" != "resume" ]; then
      # A new session that starts detached owns no branch, even if an earlier
      # session did. A resumed session keeps the branch it already owned, so
      # archiving it later still tears down what it set up.
      rm -f "$_claude_branch_marker"
    fi

    # Bootstrap output belongs in the hook log, not Claude's context.
    # An unarchived worktree still has its .workspace marker but no databases,
    # so --once would skip it. Keep the archived marker until setup succeeds.
    if [ -f "$_claude_archived_marker" ]; then
      # Until setup succeeds the worktree is not fully torn down either, so a
      # later archive must run again.
      printf 'started\n' > "$_claude_archived_marker"
      sh "$WORKSPACE_LIB/bootstrap.sh" >&2
      rm -f "$_claude_archived_marker"
      exit 0
    fi
    exec sh "$WORKSPACE_LIB/bootstrap.sh" --once >&2
    ;;
  session-end)
    [ -f "$_claude_branch_marker" ] || exit 0
    git symbolic-ref -q HEAD >/dev/null && exit 0
    # A rebase or bisect detaches HEAD on purpose; that is not an archive.
    for _claude_in_progress in rebase-merge rebase-apply BISECT_LOG; do
      [ ! -e "$_claude_git_dir/$_claude_in_progress" ] || exit 0
    done
    ! _claude_archive_running || exit 0
    # Ending detached again after a complete archive, with no session start
    # in between, is not a second archive.
    [ "$(cat "$_claude_archived_marker" 2>/dev/null || true)" != "complete" ] || exit 0

    # Teardown may stop partway, so mark the worktree for a full bootstrap
    # before starting. A failed archive is attempted again on the next archive.
    printf 'started\n' > "$_claude_archived_marker"
    # SessionEnd hooks get at most 60 seconds; archive may need longer. The
    # job runs in its own session so it survives Claude Code stopping the
    # hook's process group, and records its own PID (via rename, so readers
    # never see a partial file) before working. macOS has no setsid command,
    # but ships Perl.
    if command -v setsid >/dev/null 2>&1; then
      set -- setsid
    elif command -v perl >/dev/null 2>&1; then
      set -- perl -MPOSIX=setsid -e 'setsid(); exec @ARGV or die "exec: $!"'
    else
      set --
    fi
    "$@" nohup sh -c '
      printf "%s\n" "$$" > "$3.$$" && mv -f "$3.$$" "$3"
      printf "=== archive %s\n" "$(date)"
      if sh "$1/archive.sh"; then
        _state=complete
      else
        _state=failed
        echo "Archive failed; it will be retried the next time this session is archived."
      fi
      printf "%s\n" "$_state" > "$2.$$" && mv -f "$2.$$" "$2"
      rm -f "$3"
    ' workspace-claude-archive "$WORKSPACE_LIB" "$_claude_archived_marker" \
      "$_claude_archiving_marker" >> "$_claude_log" 2>&1 &
    _claude_job=$!
    # Return only once the job is visible to a session start that follows.
    while [ ! -s "$_claude_archiving_marker" ] && kill -0 "$_claude_job" 2>/dev/null; do
      sleep 0.1
    done
    exit 0
    ;;
  *)
    echo "workspace claude-hook: unknown event '$_claude_event'" >&2
    exit 1
    ;;
esac
