#!/bin/sh
# workspace init — Set up a project to work with workspace CLI.
#
# Flow:
#   1. Patch database.yml for workspace isolation (idempotent)
#   2. Create conductor.json
#   3. Create .conductor/ directory
#   4. Create .superconductor/config.json
#   5. Create .superset/config.json
#   6. Create Codex environment and lifecycle hook config
#   7. Create bin/workspace-seed (commented scaffold)
#   8. Add .workspace to .gitignore

set -e

WORKSPACE_LIB="$(dirname "$0")/../lib"
. "$WORKSPACE_LIB/common.sh"
. "$WORKSPACE_LIB/db.sh"

header "Initializing workspace support"

# ── Patch database.yml ──────────────────────────────────────────

patch_database_yml

# ── Create conductor.json ───────────────────────────────────────

if [ -f conductor.json ]; then
  step "conductor.json already exists"
else
  cat > conductor.json <<'EOF'
{
  "scripts": {
    "setup": "workspace bootstrap",
    "run": "workspace run",
    "archive": "workspace archive"
  }
}
EOF
  ok "Created conductor.json"
fi

# ── Create .conductor/ directory ────────────────────────────────

if [ -d .conductor ]; then
  step ".conductor/ already exists"
else
  mkdir -p .conductor
  ok "Created .conductor/"
fi

# ── Create .superconductor/config.json ──────────────────────────

if [ -f .superconductor/config.json ]; then
  step ".superconductor/config.json already exists"
else
  mkdir -p .superconductor
  cat > .superconductor/config.json <<'EOF'
{
  "setup": ["workspace bootstrap"],
  "run": ["workspace run"]
}
EOF
  ok "Created .superconductor/config.json"
fi

# ── Create .superset/config.json ────────────────────────────────

if [ -f .superset/config.json ]; then
  step ".superset/config.json already exists"
else
  mkdir -p .superset
  cat > .superset/config.json <<'EOF'
{
  "setup": ["workspace bootstrap"],
  "teardown": ["workspace archive"]
}
EOF
  ok "Created .superset/config.json"
fi

# ── Create Codex local environment ─────────────────────────────────────────

if [ -f .codex/environments/environment.toml ]; then
  step ".codex/environments/environment.toml already exists"
else
  mkdir -p .codex/environments
  _codex_environment_name=$(basename "$(pwd)" \
    | tr -cs 'a-zA-Z0-9._-' '-' \
    | sed 's/^-*//;s/-*$//')
  [ -n "$_codex_environment_name" ] || _codex_environment_name="workspace"
  cat > .codex/environments/environment.toml <<EOF
# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "$_codex_environment_name"

[setup]
script = "workspace bootstrap"

[[actions]]
name = "Run"
icon = "run"
command = "workspace run"

[[actions]]
name = "Archive workspace"
icon = "tool"
command = "workspace archive"
EOF
  ok "Created .codex/environments/environment.toml"
fi

# SessionEnd does not distinguish archive from ordinary close/idle events.
# Deferred prune is intentionally reconciliation-only: it cleans resources
# after Git confirms that Codex removed the associated worktree.
if [ -f .codex/hooks.json ]; then
  step ".codex/hooks.json already exists"
else
  mkdir -p .codex
  cat > .codex/hooks.json <<'EOF'
{
  "description": "Clean resources after Codex removes managed worktrees.",
  "hooks": {
    "SessionEnd": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "workspace prune --deferred",
            "timeout": 5,
            "statusMessage": "Scheduling workspace cleanup"
          }
        ]
      }
    ]
  }
}
EOF
  ok "Created .codex/hooks.json"
fi

# ── Create bin/workspace-seed ────────────────────────────────────

if [ -f bin/workspace-seed ]; then
  step "bin/workspace-seed already exists"
else
  cat > bin/workspace-seed <<'EOF'
#!/bin/sh
# Seed the workspace database after schema load.
# Uncomment the line that matches your project's seed strategy.
#
# Fixtures (test data loaded into dev):
#   bin/rails db:fixtures:load
#
# Seeds file (db/seeds.rb):
#   bin/rails db:seed
#
# Custom rake task:
#   bin/rails plan:seed
#
# Nothing needed? Delete this file.

EOF
  chmod +x bin/workspace-seed
  ok "Created bin/workspace-seed (edit to configure seeding)"
fi

# ── Add .workspace to .gitignore ────────────────────────────────

if [ -f .gitignore ] && grep -qxF '.workspace' .gitignore; then
  step ".workspace already in .gitignore"
elif [ -f .gitignore ]; then
  [ -z "$(tail -c1 .gitignore 2>/dev/null)" ] || printf '\n' >> .gitignore
  printf '.workspace\n' >> .gitignore
  ok "Added .workspace to .gitignore"
else
  printf '.workspace\n' > .gitignore
  ok "Created .gitignore with .workspace"
fi

printf "\n${_green}  ✓${_reset} ${_bold}Project is now workspace-ready${_reset}\n"
